name: Cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
      strategy:​
        matrix:​
          browser:[chrome, firefox, edge]​
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.13.1'
    
    - name: Install project dependencies
      run: npm install
      
    - name: Run Cypress tests
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      run: npx cypress run  --browser ${{ matrix.browser }}​ --config-file=cypress.config.js --record true --key ${{ secrets.CYPRESS_RECORD_KEY }}
